In [ ]:
# Importing numpy library using alias
import numpy as np

In [ ]:
# Version and configuration of NumPy
print(np.__version__)

2.0.2


In [ ]:
# Creating a vector filled with zeros of size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Find help/documentation for a NumPy function from the command line
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [ ]:
# Create a zero vector of size 10 with the fifth element as 1
ap = np.zeros(10)
ap[4] = 1
ap

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
# Create a vector with values from 10 to 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
# Reversing a vector
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [ ]:
# Creating a 3x3 matrix with values from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#Finding indices of non-zero elements in an array
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4]),)

In [ ]:
# Creating a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Generate a 3x3x3 array with random values
b = np.random.random((3,3,3))
b

array([[[0.48245829, 0.38158226, 0.73301367],
        [0.14407961, 0.82893726, 0.69671972],
        [0.67373898, 0.95182012, 0.30448515]],

       [[0.49874369, 0.87570292, 0.0871797 ],
        [0.08710662, 0.60962394, 0.62837007],
        [0.46487771, 0.94162128, 0.51641268]],

       [[0.94779484, 0.17420138, 0.46352616],
        [0.05301736, 0.34632537, 0.08114687],
        [0.4444505 , 0.3066557 , 0.93542886]]])

In [ ]:
# Find the min and max values in a 10x10 random matrix
np.random.random((10,10)).min()

np.float64(0.011992879613243357)

In [ ]:
# Calculate the mean of a random vector of size 30
np.random.random(30).mean()

np.float64(0.4688268521807408)

In [ ]:
# Create a 2D array with 1s on the border and 0s inside
carray = np.ones((10,10))
carray[1:-1,1:-1] = 0
carray

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# What is the result of operations like 0 * np.nan, np.nan == np.nan, etc
0*np.nan, np.nan == np.nan

(nan, False)

In [ ]:
#Create a matrix with values below the diagonal
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
# Create a checkerboard pattern in an 8x8 matrix
checkp = np.zeros((8,8),dtype=int)
checkp[1::2,::2] = 1
checkp[::2,1::2] = 1
checkp

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
# Find the index of a flat element in a 3D shape
np.unravel_index(100,(6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

In [ ]:
# Create a checkerboard pattern using NumPy's tile function
checkerboard = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(checkerboard)

In [ ]:
#  Normalize a matrix (values between 0 and 1)
norm = np.random.random((10,10))
zmax, zmin = norm.max(), norm.min()
norm = (norm - zmin)/(zmax - zmin)
norm

array([[0.37886637, 0.09667196, 0.05187519, 0.96700663, 0.06143959,
        0.19569447, 0.        , 0.40039414, 0.32784525, 0.31582328],
       [0.51283333, 0.24032146, 0.98156194, 0.94810392, 0.64470914,
        0.61911316, 0.9765944 , 0.66849273, 0.77957983, 0.77125213],
       [0.91412053, 0.72821894, 0.16864508, 0.5051459 , 0.0477097 ,
        0.02196748, 0.94962671, 0.05402959, 0.90038267, 0.63588894],
       [0.84073722, 0.48831703, 0.55876379, 0.38324353, 0.94315123,
        0.04831719, 0.45367096, 1.        , 0.54347294, 0.73123707],
       [0.35657957, 0.38915693, 0.27220817, 0.63032909, 0.87753756,
        0.96419454, 0.59341911, 0.87492214, 0.52785916, 0.19490689],
       [0.61853267, 0.37154324, 0.81522654, 0.48072731, 0.44311212,
        0.90188351, 0.20692609, 0.37488617, 0.73074222, 0.80159031],
       [0.99671195, 0.50657214, 0.74360159, 0.01362342, 0.97860198,
        0.44565253, 0.28884077, 0.34537826, 0.60370538, 0.69382403],
       [0.24116516, 0.99991191, 0.9239370

In [ ]:
# Define a custom data type for storing color (RGBA)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

In [ ]:
# Perform a matrix multiplication between two matrices
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [ ]:
# Negate values between two given numbers in a vector
neg = np.arange(11)
neg[(3 < neg) & (neg < 8)] *= -1
neg

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [ ]:
# output of sum(range(5), -1) vs np.sum(range(5), -1)
output = sum(range(5), -1)
output1 = np.sum(range(5), -1)
output, output1

(9, np.int64(10))

In [ ]:
# Which NumPy vector operations are legal or illegal
legal = np.array([0, 0, 0, 0])
illegal = np.array([1, 0, 0, 0])
legal, illegal
#

(array([0, 0, 0, 0]), array([1, 0, 0, 0]))

In [ ]:
# What happens when you divide integers or floats by zero in NumPy
np.array([1, 2, 3, 4]) / 0

/tmp/ipython-input-2597122814.py:2: RuntimeWarning: divide by zero encountered in divide
  np.array([1, 2, 3, 4]) / 0


array([inf, inf, inf, inf])

In [ ]:
# How do you round a float array away from zero
np.array([1, 2, 3, 4]).round()

array([1, 2, 3, 4])

In [ ]:
# Extract the integer part of a float using multiple methods
np.array([1.2, 2.3, 3.4, 4.5]).astype(int)

array([1, 2, 3, 4])

In [ ]:
# Create a 5x5 matrix with row values ranging from 0 to 4
rowmatrix = np.zeros((5,5))
rowmatrix += np.arange(5)
rowmatrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [ ]:
# Use a generator to create a NumPy array
generate = np.fromiter(range(10),dtype=float,count=-1)
generate

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Create an array with evenly spaced values between 0 and 1 (excluded)
evenspaced = np.linspace(0,1,11,endpoint=False)[1:]
evenspaced

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [ ]:
# Sort a random array
sort = np.random.random(10)
sort.sort()
sort

array([0.11882757, 0.28181738, 0.34095355, 0.403384  , 0.53663095,
       0.71406994, 0.72543759, 0.84759331, 0.87234262, 0.95905656])

In [ ]:
# Sum an array faster than using np.sum
np.add.reduce(np.arange(10))

np.int64(45)

In [ ]:
# Check if two arrays are equal
a1 = np.array([1, 2, 3, 4])
a2 = np.array([1, 2, 3, 4])
np.array_equal(a1, a2)

True

In [ ]:
# Make a NumPy array read-only
a3 = np.array([1, 2, 3, 4])
a3.flags.writeable = False

**Intermediate Functions**

In [ ]:
# Convert Cartesian coordinates to polar coordinates
cartesian = np.random.random((10, 2))
x,y = cartesian[:,0], cartesian[:,1]
r = np.hypot(x,y) # radius
t = np.arctan2(y,x) # theta
print(r)
print(t)

[0.98795909 0.84392388 1.1117497  0.95541812 0.60561225 0.75832525
 0.99606213 0.96991813 0.73106428 1.28029917]
[1.41996411 0.90640963 1.10184682 1.0999605  0.7374707  0.79148862
 0.11699628 0.93035247 1.0160954  0.73142709]


In [ ]:
# Replace the maximum value in an array with zero
maxarray = np.random.random(10)
maxarray[maxarray.argmax()] = 0
maxarray

array([0.40034908, 0.22959721, 0.82802883, 0.        , 0.20703179,
       0.6718189 , 0.52843434, 0.06086937, 0.73892451, 0.88395257])

In [ ]:
# Create a structured array for (x, y) coordinate pairs
Strucarray = np.array(3, dtype=[('x', float), ('y', float)])
Strucarray

array((3., 3.), dtype=[('x', '<f8'), ('y', '<f8')])

In [ ]:
# Create a Cauchy matrix using two arrays
array1 = np.arange(8)
array2 = array1 + 0.5
cauchy = 1.0 / np.subtract.outer(array1, array2)
cauchy

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

In [ ]:
# Find the range of values for each NumPy scalar type
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [ ]:
# Display all values in a large array
np.set_printoptions(threshold=float("inf"))
largearray = np.zeros((16,16))
largearray

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [ ]:
# Find the closest value to a given scalar in an array
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

9


In [ ]:
# Create a structured array with position and color fields
structured = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),])
structured

array([(([0.], [0.]),), (([0.], [0.]),), (([0.], [0.]),), (([0.], [0.]),),
       (([0.], [0.]),), (([0.], [0.]),), (([0.], [0.]),), (([0.], [0.]),),
       (([0.], [0.]),), (([0.], [0.]),)],
      dtype=[('position', [('x', '<f8', (1,)), ('y', '<f8', (1,))])])

In [ ]:
# Compute pairwise distances between coordinates
coordinates = np.random.random((10,2))
X,Y = np.atleast_2d(coordinates[:,0], coordinates[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
D

array([[0.        , 0.57150336, 0.26536405, 0.31143837, 0.68363353,
        0.69088735, 0.47560004, 0.5732825 , 0.76969604, 0.17316832],
       [0.57150336, 0.        , 0.78429154, 0.60394381, 0.26622311,
        0.26712213, 0.2944654 , 0.9877432 , 0.52003787, 0.41701237],
       [0.26536405, 0.78429154, 0.        , 0.2715969 , 0.93528247,
        0.94205154, 0.60161177, 0.32810014, 0.82919644, 0.36990595],
       [0.31143837, 0.60394381, 0.2715969 , 0.        , 0.8113965 ,
        0.81655455, 0.36171013, 0.38380482, 0.5581485 , 0.26381743],
       [0.68363353, 0.26622311, 0.93528247, 0.8113965 , 0.        ,
        0.00838549, 0.55175855, 1.18734945, 0.78185419, 0.57412202],
       [0.69088735, 0.26712213, 0.94205154, 0.81655455, 0.00838549,
        0.        , 0.55413314, 1.19300233, 0.78142601, 0.5803243 ],
       [0.47560004, 0.2944654 , 0.60161177, 0.36171013, 0.55175855,
        0.55413314, 0.        , 0.73391914, 0.31822303, 0.30530526],
       [0.5732825 , 0.9877432 , 0.3281001

In [ ]:
# Cast a float array to integer type in place
floatarray = np.arange(10, dtype=np.float32)
floatarray = floatarray.astype(np.int32, copy=False)
floatarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
# Read data from a file with missing values
# To data from dataset import pandas library
import pandas as pd
missingdata = pd.read_csv("/content/drive/MyDrive/Sep_2025_GenAI/Python/data/2015.csv")
np.genfromtxt(missingdata, delimiter=",", dtype="float",
              filling_values=np.nan)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [ ]:
# Iterate through all elements in a NumPy array with indices
iterate = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(iterate):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
# Create a 2D Gaussian-like array
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
x,y

(array([[-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.3333333

In [ ]:
# Randomly place a specific number of elements in a 2D array
place = np.zeros((5,5))
np.put(place, np.random.choice(range(5*5), 3, replace=False),1)
place
#

array([[1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Subtract the row mean from a matrix
subtract = np.random.rand(5, 10)
subtract - subtract.mean(axis=1, keepdims=True)

array([[ 0.57776377, -0.1681369 , -0.39017675, -0.27642841,  0.25310353,
        -0.34284759, -0.16727105, -0.04657036,  0.58435269, -0.02378893],
       [-0.17345254, -0.35321043,  0.53167904, -0.00595165,  0.33920151,
        -0.36328557,  0.28885242,  0.0732153 , -0.39728327,  0.06023517],
       [-0.00336352,  0.31130481, -0.19597794, -0.21035394, -0.33146248,
         0.55734996, -0.03425269, -0.30052121,  0.49928304, -0.29200603],
       [ 0.51227819, -0.15050958,  0.15874369,  0.53459142,  0.17484352,
        -0.08297611, -0.37024262, -0.1238028 , -0.21675833, -0.43616737],
       [-0.36286099, -0.16412484,  0.28028111,  0.37593333, -0.19691809,
         0.51062639, -0.13972994, -0.25191692,  0.03424832, -0.08553837]])

In [ ]:
# Sort a 2D array based on the values of one column
arr2 = np.random.randint(0,10,(3,3))
arr2[arr2[:,1].argsort()]

array([[2, 1, 1],
       [2, 5, 8],
       [8, 6, 0]])

In [ ]:
# Check if a 2D array contains any null (zero-only) columns
arr3 = np.random.randint(0,3,(3,10))
(~arr3.any(axis=0)).any()

np.False_

In [ ]:
# Find the nearest value to a given number in a NumPy array
nearvalue = np.random.uniform(0, 10, 10) # Sample array
target = 5.5 # Target value
index = (np.abs(nearvalue - target)).argmin()
nearest_value = nearvalue[index]
print(f"Array: {nearvalue}")
print(f"Target value: {target}")
print(f"Nearest value: {nearest_value}")

Array: [5.74472478 9.2796852  0.92114633 8.81641557 1.9366009  8.89897343
 7.7371862  8.61378988 1.08481726 1.87792114]
Target value: 5.5
Nearest value: 5.744724778054293


In [ ]:
# Create a NumPy subclass with custom attributes


In [ ]:
# Create a NumPy subclass with custom attributes
class MyArray(np.ndarray):
    def __new__(cls, input_array, custom_attribute=None):
        # Input array is an already created numpy ndarray
        # Cast the input array to our type
        obj = np.asarray(input_array).view(cls)
        # Add the new attribute to the created instance
        obj.custom_attribute = custom_attribute
        # Finally, return the created object
        return obj

    def __array_finalize__(self, obj):
        # __array_finalize__ is called after new from first
        # argument of the view method.
        # See the description of the __array_finalize__ method for more details
        if obj is None: return
        self.custom_attribute = getattr(obj, 'custom_attribute', None)

# Example usage
my_array = MyArray([1, 2, 3, 4, 5], custom_attribute="This is a custom attribute")
print(my_array)
print(my_array.custom_attribute)

[1 2 3 4 5]
This is a custom attribute


In [ ]:
# Increment elements in an array using an index array with repeats


In [ ]:
# Increment elements in an array using an index array with repeats
Z = np.zeros(10)
indices = np.array([0, 1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
np.add.at(Z, indices, 1)
print(Z)

[1. 1. 2. 3. 4. 0. 0. 0. 0. 0.]


In [ ]:
# Accumulate values into an array based on indices


In [ ]:
# Accumulate values into an array based on indices
a = np.array([1, 2, 3, 4, 5])
np.add.accumulate(a)

array([ 1,  3,  6, 10, 15])

In [ ]:
# Count unique colors in a 3D image array


In [ ]:
# Count unique colors in a 3D image array
image = np.random.randint(0, 256, (10, 10, 3), dtype=np.uint8) # Example 3D image array (height, width, channels)
unique_colors, counts = np.unique(image.reshape(-1, image.shape[-1]), axis=0, return_counts=True)
print("Unique colors:\n", unique_colors)
print("\nCounts of unique colors:", counts)
print("\nNumber of unique colors:", len(unique_colors))

Unique colors:
 [[  6 158 132]
 [ 10  57  62]
 [ 10 224  72]
 [ 11  18 196]
 [ 12 176  56]
 [ 13 131 168]
 [ 15 142 190]
 [ 17 126  33]
 [ 23 163 161]
 [ 24 141  92]
 [ 26 206 181]
 [ 31 103   6]
 [ 31 251 217]
 [ 34 252 231]
 [ 36 172 156]
 [ 46 205 239]
 [ 51  26 193]
 [ 51  31 205]
 [ 54  98  33]
 [ 55 149 181]
 [ 59  12 186]
 [ 62 149   4]
 [ 65  19 234]
 [ 66  40  19]
 [ 70  28 125]
 [ 70  52 205]
 [ 71 232  48]
 [ 77 207 103]
 [ 77 243  76]
 [ 79  91 176]
 [ 79 243  71]
 [ 84   3 203]
 [ 87  93 104]
 [ 90 110 150]
 [ 99 123 207]
 [103 119   1]
 [106  25  58]
 [109  69 148]
 [110 102 189]
 [113  68 184]
 [113 196  14]
 [115 154  13]
 [118 223  30]
 [119 152  16]
 [120 100 252]
 [122  33 206]
 [122 107 199]
 [124  48  44]
 [128  25  79]
 [129  37 248]
 [129  63  88]
 [129  93 243]
 [135 122 189]
 [136 200 108]
 [141  26 140]
 [151 151 247]
 [155 112 126]
 [157 239  30]
 [158 125  29]
 [159   8 251]
 [160  46  14]
 [160 156 110]
 [164 254 244]
 [168 252 126]
 [171 137 100]
 [173  79

In [ ]:
# Compute the sum across the last two axes of a 4D array


In [ ]:
# Compute the sum across the last two axes of a 4D array
array_4d = np.random.rand(2, 3, 4, 5) # Example 4D array

# Sum across the last two axes (axis 2 and axis 3)
sum_across_last_two_axes = np.sum(array_4d, axis=(-2, -1)) # Using negative indices for the last two axes

print("Original 4D array shape:", array_4d.shape)
print("Sum across the last two axes shape:", sum_across_last_two_axes.shape)
print("\nSum across the last two axes:\n", sum_across_last_two_axes)

Original 4D array shape: (2, 3, 4, 5)
Sum across the last two axes shape: (2, 3)

Sum across the last two axes:
 [[ 9.20590671  9.67628157 10.7539204 ]
 [11.08124652 10.80917224  7.40249131]]


In [ ]:
# Calculate means of grouped values in an array

In [ ]:
# Calculate means of grouped values in an array
# Example array and grouping array
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
groups = np.array([1, 1, 2, 2, 3, 3, 1, 1, 2, 2])

# Find unique groups
unique_groups = np.unique(groups)

# Calculate mean for each group
for group in unique_groups:
    mean_value = np.mean(data[groups == group])
    print(f"Mean for group {group}: {mean_value}")

Mean for group 1: 45.0
Mean for group 2: 65.0
Mean for group 3: 55.0


In [ ]:
# Efficiently get the diagonal of a matrix dot product


In [ ]:
# Efficiently get the diagonal of a matrix dot product
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)

# Using np.einsum
diagonal_einsum = np.einsum('ij,ji->i', A, B)

# Using dot product and diagonal (less efficient for large matrices)
# diagonal_dot = np.diag(np.dot(A, B))

print("Diagonal using einsum:\n", diagonal_einsum)
# print("\nDiagonal using dot and diag:\n", diagonal_dot) # Uncomment to compare

Diagonal using einsum:
 [1.76766029 2.08145997 1.16306662 0.5849318  1.3960065 ]


**Advanced**

In [ ]:
# Interleave a vector with a fixed number of zeros
vector = np.array([1, 2, 3, 4, 5])
num_zeros = 3

# Create a new array with the interleaved zeros
# The new size will be the original size plus (original size - 1) * number of zeros
interleaved_size = len(vector) + (len(vector) - 1) * num_zeros
interleaved_vector = np.zeros(interleaved_size)

# Place the original vector elements
interleaved_vector[::num_zeros + 1] = vector

print("Original vector:", vector)
print("Interleaved vector:", interleaved_vector)

Original vector: [1 2 3 4 5]
Interleaved vector: [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [ ]:
# Multiply a (5,5,3) array with a (5,5) array element-wise
array_3d = np.random.rand(5, 5, 3)
array_2d = np.random.rand(5, 5)

# Element-wise multiplication using broadcasting
result = array_3d * array_2d[:, :, np.newaxis]

print("Shape of 3D array:", array_3d.shape)
print("Shape of 2D array:", array_2d.shape)
print("Shape of the result:", result.shape)
print("\nResult of element-wise multiplication:\n", result)

Shape of 3D array: (5, 5, 3)
Shape of 2D array: (5, 5)
Shape of the result: (5, 5, 3)

Result of element-wise multiplication:
 [[[0.07157432 0.12597076 0.47594573]
  [0.39089859 0.33061305 0.32536574]
  [0.17072698 0.17907264 0.21092815]
  [0.94617457 0.20263214 0.14330379]
  [0.2161558  0.10814528 0.16417549]]

 [[0.35175075 0.37306453 0.02825852]
  [0.11072397 0.44217825 0.48069504]
  [0.25458953 0.04078339 0.05656943]
  [0.46329243 0.6342911  0.95022214]
  [0.16561956 0.13532516 0.09472162]]

 [[0.00299274 0.10596662 0.03512434]
  [0.01922185 0.11341127 0.14266544]
  [0.17858567 0.16327847 0.23609591]
  [0.01069278 0.01705084 0.0537444 ]
  [0.01426389 0.32191054 0.02134806]]

 [[0.00243451 0.1863405  0.01698723]
  [0.39426421 0.67397832 0.1638562 ]
  [0.00273446 0.01386243 0.01720112]
  [0.27437934 0.06048956 0.00486881]
  [0.0421475  0.20475043 0.17642177]]

 [[0.18615256 0.23662703 0.15486436]
  [0.12789687 0.41876981 0.41141284]
  [0.08957317 0.61890851 0.30390719]
  [0.2326228  

In [ ]:
# Swap two rows in a matrix
matrix = np.arange(25).reshape(5, 5)
print("Original matrix:\n", matrix)

# Swap row 1 (index 0) and row 3 (index 2)
matrix[[0, 2]] = matrix[[2, 0]]

print("\nMatrix after swapping rows 1 and 3:\n", matrix)

Original matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Matrix after swapping rows 1 and 3:
 [[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
# Extract unique line segments from triangle definitions
# Example triangle definitions (each row represents a triangle with vertex indices)
triangles = np.array([[0, 1, 2],
                      [0, 2, 3],
                      [1, 2, 4],
                      [2, 3, 5]])

# Get all line segments from the triangles
# Each triangle (A, B, C) gives three segments: (A, B), (B, C), (C, A)
segments = triangles[:, [0, 1]].tolist() + triangles[:, [1, 2]].tolist() + triangles[:, [2, 0]].tolist()
segments = np.array(segments)

# Sort the vertices within each segment to treat (A, B) and (B, A) as the same segment
segments.sort(axis=1)

# Find unique segments
unique_segments = np.unique(segments, axis=0)

print("Original triangles:\n", triangles)
print("\nAll segments (including duplicates and reversed):\n", segments)
print("\nUnique line segments:\n", unique_segments)

Original triangles:
 [[0 1 2]
 [0 2 3]
 [1 2 4]
 [2 3 5]]

All segments (including duplicates and reversed):
 [[0 1]
 [0 2]
 [1 2]
 [2 3]
 [1 2]
 [2 3]
 [2 4]
 [3 5]
 [0 2]
 [0 3]
 [1 4]
 [2 5]]

Unique line segments:
 [[0 1]
 [0 2]
 [0 3]
 [1 2]
 [1 4]
 [2 3]
 [2 4]
 [2 5]
 [3 5]]


In [ ]:
# Recreate an array from a bincount
# Example bincount array
bincount_array = np.array([0, 1, 2, 3, 4, 0])

# Recreate the original array using np.repeat
# The values are the indices, and the repeats are the counts
recreated_array = np.repeat(np.arange(len(bincount_array)), bincount_array)

print("Original bincount array:", bincount_array)
print("Recreated array:", recreated_array)

Original bincount array: [0 1 2 3 4 0]
Recreated array: [1 2 2 3 3 3 4 4 4 4]


In [ ]:
# Compute a moving average using a sliding window
def moving_average(data, window_size):
    if window_size <= 0 or window_size > len(data):
        raise ValueError("Window size must be positive and less than or equal to the data length.")

    # Create a convolution kernel
    weights = np.ones(window_size) / window_size

    # Use np.convolve to compute the moving average
    # 'valid' mode returns the convolution only where the arrays fully overlap
    moving_avg = np.convolve(data, weights, mode='valid')
    return moving_avg

# Example usage
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
window_size = 3
moving_avg_result = moving_average(data, window_size)

print("Original data:", data)
print(f"Moving average with window size {window_size}:\n", moving_avg_result)

Original data: [ 10  20  30  40  50  60  70  80  90 100]
Moving average with window size 3:
 [20. 30. 40. 50. 60. 70. 80. 90.]


In [ ]:
# Create a rolling 2D view from a 1D array
def rolling_window(a, window_size):

    if window_size <= 0 or window_size > a.size:
        raise ValueError("Window size must be positive and less than or equal to the array size.")

    shape = (a.size - window_size + 1, window_size)
    strides = (a.strides[0], a.strides[0])
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

# Example usage
data = np.arange(10)
window_size = 3
rolling_view = rolling_window(data, window_size)

print("Original 1D array:", data)
print(f"\nRolling 2D view with window size {window_size}:\n", rolling_view)

Original 1D array: [0 1 2 3 4 5 6 7 8 9]

Rolling 2D view with window size 3:
 [[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
# Invert booleans or negate floats in-place

# Inverting booleans in-place
bool_array = np.array([True, False, True, False])
print("Original boolean array:", bool_array)
np.logical_not(bool_array, out=bool_array) # Invert in-place
print("Inverted boolean array (in-place):", bool_array)

print("-" * 20) # Separator

# Negating floats in-place
float_array = np.array([1.5, -2.0, 3.7, -4.1])
print("Original float array:", float_array)
float_array[:] = -float_array # Negate in-place
print("Negated float array (in-place):", float_array)

Original boolean array: [ True False  True False]
Inverted boolean array (in-place): [False  True False  True]
--------------------
Original float array: [ 1.5 -2.   3.7 -4.1]
Negated float array (in-place): [-1.5  2.  -3.7  4.1]


In [ ]:
# Compute the distance from a point to multiple lines

# Define the point (x0, y0)
x0, y0 = 1, 1
point = np.array([x0, y0])
a1, b1, c1 = 1, -1, 0
a2, b2, c2 = 1, 1, -2
lines = np.array([[a1, b1, c1], [a2, b2, c2]])
# Numerator: absolute value of a*x0 + b*y0 + c
numerators = np.abs(lines[:,0]*point[0] + lines[:,1]*point[1] + lines[:,2])
# Denominator: sqrt(a^2 + b^2)
denominators = np.sqrt(lines[:,0]**2 + lines[:,1]**2)
# Compute distances for all lines
distances = numerators / denominators
print(distances)

[0. 0.]


In [ ]:
# Compute the distances from multiple points to multiple lines

points = np.array([[1, 2],[3, 4],[5, 6]])
lines = np.array([[[0, 0], [2, 2]],[[1, 1], [1, 4]]])

# Extract line start/end for broadcasting
L1 = lines[:, 0]
L2 = lines[:, 1]
x1, y1 = L1[:, 0], L1[:, 1]
x2, y2 = L2[:, 0], L2[:, 1]
# Reshape for broadcasting
x1 = x1[None, :]  # (1, n_lines)
y1 = y1[None, :]
x2 = x2[None, :]
y2 = y2[None, :]
px = points[:, 0][:, None]  # (n_points, 1)
py = points[:, 1][:, None]
# Numerator and denominator for distance formula
numerator = np.abs((x2 - x1) * (y1 - py) - (x1 - px) * (y2 - y1))  # (n_points, n_lines)
denominator = np.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)  # (1, n_lines)

distances = numerator / denominator  # shape: (n_points, n_lines)
print(distances)

[[0.70710678 0.        ]
 [0.70710678 2.        ]
 [0.70710678 4.        ]]


In [ ]:
# Extract a fixed-shaped subarray centered on a given point

def extract_subarray(arr, center, shape):
    cy, cx = center
    h, w = shape
    # Calculate start and end indices for rows and columns
    start_y = max(cy - h // 2, 0)
    end_y = min(cy + (h + 1) // 2, arr.shape[0])
    start_x = max(cx - w // 2, 0)
    end_x = min(cx + (w + 1) // 2, arr.shape[1])

    return arr[start_y:end_y, start_x:end_x]

arr = np.arange(100).reshape((10,10))
center = (5, 5)   # Center point: row 5, column 5
shape = (3, 3)    # Subarray shape: 3x3

subarray = extract_subarray(arr, center, shape)
print(subarray)


[[44 45 46]
 [54 55 56]
 [64 65 66]]


In [ ]:
# Generate overlapping subarrays from a vector

def overlapping_subarrays(arr, size, step=1):
    n = len(arr)
    if size > n:
        return np.array([])  # no subarrays if size is larger than arr
    subarrays = []
    for start in range(0, n - size + 1, step):
        subarrays.append(arr[start:start + size])
    return np.array(subarrays)

# Example
input_array = np.array([1, 2, 3, 4, 5, 6, 7])
subarray_size = 3
result = overlapping_subarrays(input_array, subarray_size)
print(result)


[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


In [ ]:
# Compute the rank of a matrix using SVD

A = np.array([[1, 2], [2, 4], [3, 6]])
# Compute SVD
U, S, VT = np.linalg.svd(A)
# Set tolerance (default is usually fine)
tol = 1e-12
rank = np.sum(S > tol)
print("Rank:", rank)


Rank: 1


In [ ]:
# Find the most frequent value in an array
arr5 = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 1])
most_frequent_value = np.bincount(arr5).argmax()
print(f"The array is: {arr5}")
print(f"The most frequent value is: {most_frequent_value}")

The array is: [1 2 3 4 5 1 2 1 1 3 4 5 6 7 8 9 1 2 3 4 5 1]
The most frequent value is: 1


In [ ]:
# Extract all 3x3 contiguous blocks from a 10x10 matrix
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view
matrix = np.arange(1, 101).reshape(10, 10)
blocks_3x3 = sliding_window_view(matrix, (3, 3))
print(blocks_3x3.shape)  # Output: (8, 8, 3, 3)

(8, 8, 3, 3)


In [ ]:
# Create a 2D symmetric matrix class
symatrix = np.array([[1, 2, 3],
                     [2, 4, 5],
                     [3, 5, 6]])
symatrix

array([[1, 2, 3],
       [2, 4, 5],
       [3, 5, 6]])

In [ ]:
# Create a 2D symmetric matrix class
class SymmetricMatrix(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        # Ensure the indices are valid
        if i < 0 or j < 0 or i >= self.shape[0] or j >= self.shape[1]:
            raise IndexError("Index out of bounds")

        # Set both (i, j) and (j, i) to the same value to maintain symmetry
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)

# Example usage:
# Create a zero matrix
sym_matrix = np.zeros((5, 5)).view(SymmetricMatrix)
print("Initial symmetric matrix:\n", sym_matrix)

# Set a value at (1, 3) - this will also set (3, 1)
sym_matrix[1, 3] = 10
print("\nMatrix after setting sym_matrix[1, 3] = 10:\n", sym_matrix)

# Set a value at (4, 0) - this will also set (0, 4)
sym_matrix[4, 0] = 25
print("\nMatrix after setting sym_matrix[4, 0] = 25:\n", sym_matrix)

# Accessing values
print("\nValue at sym_matrix[3, 1]:", sym_matrix[3, 1])
print("Value at sym_matrix[0, 4]:", sym_matrix[0, 4])

Initial symmetric matrix:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Matrix after setting sym_matrix[1, 3] = 10:
 [[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]

Matrix after setting sym_matrix[4, 0] = 25:
 [[ 0.  0.  0.  0. 25.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [25.  0.  0.  0.  0.]]

Value at sym_matrix[3, 1]: 10.0
Value at sym_matrix[0, 4]: 25.0


In [ ]:
# Compute the sum of multiple matrix-vector products at once

def sum_matrix_vector_products(matrices, vectors):
    if len(matrices) != len(vectors):
        raise ValueError("The number of matrices and vectors must be the same.")
    total = np.zeros(vectors[0].shape)
    for M, v in zip(matrices, vectors):
        total += np.dot(M, v)
    return total

# Example
matrices = np.array([[[1, 2], [3, 4]], [[2, 0], [1, 2]]])  # Two 2x2 matrices
vectors = np.array([[1, 1], [0, 1]])  # Two length-2 vectors
result = sum_matrix_vector_products(matrices, vectors)
print(result)  # Output: [3., 9.]


[3. 9.]


In [ ]:
# Compute the sum of blocks in a 2D array
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

def sum_of_blocks(matrix, block_size):
    # Extract sliding blocks
    blocks = sliding_window_view(matrix, block_size)
    # Sum over the last two dimensions (block dimensions) to get sum of each block
    block_sums = blocks.sum(axis=(-2, -1))
    return block_sums

# Example array
array_2d = np.arange(1, 17).reshape(4, 4)
block_size = (2, 2)

# Compute block sums
result = sum_of_blocks(array_2d, block_size)
print(result)

[[14 18 22]
 [30 34 38]
 [46 50 54]]


In [ ]:
# Simulate the Game of Life using NumPy

def game_of_life_step(board):
    kernel = np.array([[1, 1, 1],[1, 0, 1],[1, 1, 1]])
    padded_board = np.pad(board, pad_width=1, mode='constant', constant_values=0)
    neighbors_count = np.zeros_like(board)

    for i in range(board.shape[0]):
        for j in range(board.shape[1]):
            neighbors_count[i, j] = np.sum(padded_board[i:i+3, j:j+3] * kernel)

    new_board = ((neighbors_count == 3) | ((board == 1) & (neighbors_count == 2))).astype(int)
    return new_board

# Initialize a 10x10 grid with a glider pattern
board = np.zeros((10, 10), dtype=int)
board[1, 2] = 1
board[2, 3] = 1
board[3, 1:4] = 1
print("Initial Board:")
print(board)
# Simulate 4 steps
for step in range(4):
    board = game_of_life_step(board)
    print(f"Step {step + 1}:")
    print(board)


Initial Board:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Step 1:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Step 2:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Step 3:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Step 4:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 

In [ ]:
# Extract the top N largest values from an array

arr = np.array([5, 1, 8, 3, 9, 2, 7])
n = 3
# Get indices that would sort the array
sorted_indices = np.argsort(arr)
# Extract top n largest values using those indices from the end
top_n_values = arr[sorted_indices[-n:]]
print(top_n_values)


[7 8 9]


In [ ]:
# Create a Cartesian product of multiple input arrays

def cartesian_product(*arrays):
    # Create meshgrid for arrays
    grids = np.meshgrid(*arrays, indexing='ij')
    # Stack grids and reshape to get Cartesian product
    product = np.vstack(list(map(np.ravel, grids))).T # Convert map object to list
    return product

# Example usage
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
result = cartesian_product(a, b, c)
print(result)

[[1 3 5]
 [1 3 6]
 [1 4 5]
 [1 4 6]
 [2 3 5]
 [2 3 6]
 [2 4 5]
 [2 4 6]]


In [ ]:
# Create a record array from a regular NumPy array

arr = np.array([("Alice", 25, 5.5),("Bob", 30, 6.0),("Charlie", 22, 5.8)])
# Convert to record array using np.core.records.fromarrays
record_arr = np.core.records.fromarrays(arr.T,names='name, age, height',formats='U10, i4, f4')
print(record_arr)
print(record_arr.name)   # Access a field by attribute
print(record_arr.age)
print(record_arr.height)


[('Alice', 25, 5.5) ('Bob', 30, 6. ) ('Charlie', 22, 5.8)]
['Alice' 'Bob' 'Charlie']
[25 30 22]
[5.5 6.  5.8]


/tmp/ipython-input-3813110775.py:5: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  record_arr = np.core.records.fromarrays(arr.T,names='name, age, height',formats='U10, i4, f4')


In [ ]:
# Raise an array to the power of 3 using different methods

arr = np.array([1, 2, 3, 4, 5])
# Using the ** operator
result1 = arr ** 3
# Using np.power()
result2 = np.power(arr, 3)
# Using np.multiply() multiple times
result3 = np.multiply(np.multiply(arr, arr), arr)
# Using a loop (less efficient)
result4 = np.array([x**3 for x in arr])

print(result1)
print(result2)
print(result3)
print(result4)


[  1   8  27  64 125]
[  1   8  27  64 125]
[  1   8  27  64 125]
[  1   8  27  64 125]


In [ ]:
# Find rows in a matrix containing all elements of another matrix

def rows_containing_all_elements(large_mat, small_mat):
    # Set of elements to find
    target_elements = set(small_mat.flatten())
    result_indices = []
    for i, row in enumerate(large_mat):
        if target_elements.issubset(set(row)):
            result_indices.append(i)
    return result_indices
# Example
large_matrix = np.array([[1, 2, 3, 4],[4, 2, 1, 3],
    [1, 2, 4, 5],[5, 6, 7, 8]])
small_matrix = np.array([[1, 2],[3, 4]])
rows = rows_containing_all_elements(large_matrix, small_matrix)
print("Rows containing all elements:", rows)

Rows containing all elements: [0, 1]


In [ ]:
# Filter rows in a matrix with at least one differing value

def filter_rows_with_differences(matrix, reference_row_idx=0):
    ref_row = matrix[reference_row_idx]
    # Compare each row with the reference row for equality (element-wise)
    equal_elements = matrix == ref_row
    # Check rows that have at least one element different (not all True)
    differing_rows_mask = ~np.all(equal_elements, axis=1)
    # Filter those rows
    differing_rows = matrix[differing_rows_mask]
    return differing_rows

# Example
mat = np.array([[1, 2, 3],[1, 2, 3],
    [1, 5, 3],[4, 2, 3]])
result = filter_rows_with_differences(mat)
print(result)

[[1 5 3]
 [4 2 3]]


In [ ]:
# Convert integers to their binary matrix representation

def int_to_binary_matrix(arr, width=None):
    # Determine the width (number of bits)
    if width is None:
        max_val = np.max(arr)
        # Convert to Python integer before calling bit_length()
        width = int(max_val).bit_length()

    # Convert each integer to binary string padded to width
    bin_strs = [np.binary_repr(x, width=width) for x in arr]
    # Convert binary strings to 2D matrix of integers (bits)
    bin_matrix = np.array([[int(bit) for bit in bstr] for bstr in bin_strs], dtype=int)
    return bin_matrix

# Example
ints = np.array([3, 6, 11])
binary_matrix = int_to_binary_matrix(ints)
print(binary_matrix)

[[0 0 1 1]
 [0 1 1 0]
 [1 0 1 1]]


In [ ]:
# Extract unique rows from a 2D array

arr = np.array([[1, 2, 3],[4, 5, 6],[1, 2, 3],[7, 8, 9]])
# Extract unique rows
unique_rows = np.unique(arr, axis=0)
print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Compute inner, outer, sum, and multiplication using einsum

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Inner product: sum of element-wise products
inner = np.einsum('i,i->', a, b)
print("Inner product:", inner)
# Outer product: all pairwise products resulting in 2D array
outer = np.einsum('i,j->ij', a, b)
print("Outer product:\n", outer)
# Sum of array elements (reduce all axes)
sum_a = np.einsum('i->', a)
print("Sum of a:", sum_a)
# Element-wise multiplication (no summation)
mul = np.einsum('i,i->i', a, b)
print("Element-wise multiplication:", mul)

Inner product: 32
Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum of a: 6
Element-wise multiplication: [ 4 10 18]


In [ ]:
# Sample a 2D path at regular intervals
import numpy as np
from scipy.interpolate import interp1d

def sample_2d_path(points, interval):
    points = np.array(points)
    # Compute distances between consecutive points
    deltas = np.diff(points, axis=0)
    dist = np.sqrt((deltas ** 2).sum(axis=1))
    # Compute cumulative distance
    cumulative_dist = np.insert(np.cumsum(dist), 0, 0)
    # Define new sample distances
    new_dist = np.arange(0, cumulative_dist[-1], interval)
    # Interpolate x and y coordinates at new distances
    interp_x = interp1d(cumulative_dist, points[:, 0])
    interp_y = interp1d(cumulative_dist, points[:, 1])
    sampled_points = np.vstack((interp_x(new_dist), interp_y(new_dist))).T
    return sampled_points

path = [(0, 0), (3, 4), (6, 4), (9, 0)]
sampled = sample_2d_path(path, 2.0)
print(sampled)


[[0.  0. ]
 [1.2 1.6]
 [2.4 3.2]
 [4.  4. ]
 [6.  4. ]
 [7.2 2.4]
 [8.4 0.8]]


In [ ]:
# Filter 2D array rows that sum to a specific number using only integers

# Create a sample 2D integer array
arr = np.array([[1, 2, 3],
                [4, 0, 2],
                [1, 1, 1],
                [5, 5, 0],
                [2, 2, 2]])

# Specify the target sum
target_sum = 6
# Calculate the sum of each row
row_sums = np.sum(arr, axis=1)
# Create a boolean mask for rows that sum to the target number
mask = row_sums == target_sum
# Filter the rows using the boolean mask
filtered_rows = arr[mask]
print("Original array:\n", arr)
print(f"\nRows that sum to {target_sum}:\n", filtered_rows)

In [ ]:
# Stack arrays vertically and horizantally

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
vertical = np.vstack((a, b))
print("Vertical stack:\n", vertical)
horizontal = np.hstack((a, b))
print("Horizontal stack:\n", horizontal)

Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack:
 [1 2 3 4 5 6]


In [ ]:
# Apply a custom function to each element of an array

def custom_func(x):
    return x * 2 + 1

arr = np.array([1, 2, 3, 4, 5])
vectorized_func = np.vectorize(custom_func)
result = vectorized_func(arr)
print(result)

[ 3  5  7  9 11]


In [ ]:
# Remove duplicate rows in a 2D array

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9]])

unique_rows = np.unique(arr, axis=0)
print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# filter rows based on a specific column value

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 2, 9],
    [10, 11, 3]])

target_value = 2
filtered_rows = arr[arr[:, 1] == target_value]
print(filtered_rows)

[[1 2 3]
 [7 2 9]]


In [ ]:
#  Find column-wise and row-wise minimum/maximum indices

arr = np.array([
    [9, 2, 7],
    [4, 5, 6],
    [3, 8, 1]])

# Column-wise minimum indices (index of min value in each column)
col_min_indices = np.argmin(arr, axis=0)
print("Column-wise min indices:", col_min_indices)

# Column-wise maximum indices
col_max_indices = np.argmax(arr, axis=0)
print("Column-wise max indices:", col_max_indices)

# Row-wise minimum indices (index of min value in each row)
row_min_indices = np.argmin(arr, axis=1)
print("Row-wise min indices:", row_min_indices)

# Row-wise maximum indices
row_max_indices = np.argmax(arr, axis=1)
print("Row-wise max indices:", row_max_indices)

Column-wise min indices: [2 0 2]
Column-wise max indices: [0 2 0]
Row-wise min indices: [1 0 2]
Row-wise max indices: [0 2 1]


In [ ]:
#Replace NaN values in an array with the column mean

def replace_nan_with_col_mean(arr):
    # Compute column means ignoring NaNs
    col_means = np.nanmean(arr, axis=0)
    # Find indices where NaNs are present
    inds = np.where(np.isnan(arr))
    # Replace NaNs with corresponding column means
    arr[inds] = np.take(col_means, inds[1])
    return arr

# Example
arr = np.array([
    [1, 2, np.nan],
    [4, np.nan, 6],
    [7, 8, 9]
], dtype=float)

result = replace_nan_with_col_mean(arr)
print(result)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [ ]:
# Flatten and sort a 2D array

def replace_nan_with_col_mean(arr):
    col_means = np.nanmean(arr, axis=0)
    inds = np.where(np.isnan(arr))
    arr[inds] = np.take(col_means, inds[1])
    return arr

arr = np.array([[1, 2, np.nan],[4, np.nan, 6],[7, 8, 9]], dtype=float)
result = replace_nan_with_col_mean(arr)
print(result)


[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [ ]:
# Calculate the correlation coefficient between two vectors

a = np.array([1, 4, 6])
b = np.array([1, 2, 3])
corr_matrix = np.corrcoef(a, b)
corr_coef = corr_matrix[0, 1]
print(corr_coef)

0.9933992677987827
